spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/xmen"
    username: <username/>
    password: <password/>

  cache:
    type: redis
  redis:
    time-to-live: 300000

springdoc:
  packagesToScan: com.meli.xmen.api.v1.controller
  springdoc:
    api-docs:
      path: /api-docs